#!/usr/bin/env python3
"""Message channel between the Chief of Staff (via the Mini) and Claude: draft PR #99.

  python3 scripts/owb_thread.py post "message text"        # posts as [Chief]
  python3 scripts/owb_thread.py post -f report.md           # post a file
  python3 scripts/owb_thread.py post --re 5963045774 -f r.md # claim one Claude message before acting; refused if a [Chief]
                                                            # reply to it exists. Post results after with plain `post`.
  python3 scripts/owb_thread.py read                        # comments since the last read
  python3 scripts/owb_thread.py read --all                  # whole thread
  python3 scripts/owb_thread.py wait --timeout 1800         # block until Claude replies (polls every 60 s)
  python3 scripts/owb_thread.py status                      # one line: unread Claude messages? (exit 10 if any)

Run `status` (or `read`) at the start of every session and before telling Ben anything is "waiting on Claude".
Every report to Ben ends with "Thread read to #<id>" so a stale read is visible.

Auth: GH_TOKEN or GITHUB_TOKEN from the environment, else `gh auth token`. Never print or commit the token.
The last-read comment id is kept in ~/.owb_thread_state (outside the repo).
Rules: never merge or close PR #99; never paste secrets into a message.
"""
import argparse, json, os, subprocess, sys, time, urllib.request

REPO = "TheLaughingGod1986/orbit-with-ben"
PR = int(os.environ.get("OWB_THREAD_PR", "99"))
STATE = os.path.expanduser("~/.owb_thread_state")
CLAUDE_MARK = "Generated by [Claude Code]"
CHIEF_TAG = "[Chief]"


def token():
    t = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if t:
        return t
    try:
        return subprocess.run(["gh", "auth", "token"], capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        sys.exit("No GitHub token: set GH_TOKEN, or run `gh auth login` once.")


def api(method, path, body=None):
    req = urllib.request.Request(
        f"https://api.github.com/repos/{REPO}{path}", method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"Authorization": f"Bearer {token()}", "Accept": "application/vnd.github+json",
                 "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "owb-thread"})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def comments():
    out, page = [], 1
    while True:
        batch = api("GET", f"/issues/{PR}/comments?per_page=100&page={page}")
        out += [c for c in batch if c.get("user", {}).get("type") != "Bot"]   # skip Vercel etc.
        if len(batch) < 100:
            return out
        page += 1


def last_seen():
    try:
        return int(open(STATE).read().strip())
    except Exception:
        return 0


def mark(cid):
    with open(STATE, "w") as f:
        f.write(str(cid))


def show(c):
    who = "CLAUDE" if CLAUDE_MARK in c["body"] else ("CHIEF" if c["body"].lstrip().startswith(CHIEF_TAG) else c["user"]["login"])
    print(f"--- #{c['id']} {who} {c['created_at']}\n{c['body'].strip()}\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("post"); p.add_argument("text", nargs="?"); p.add_argument("-f", "--file")
    p.add_argument("--re", type=int, help="id of the Claude comment this answers; refuse if already answered")
    r = sub.add_parser("read"); r.add_argument("--all", action="store_true")
    w = sub.add_parser("wait"); w.add_argument("--timeout", type=int, default=1800)
    sub.add_parser("status")
    a = ap.parse_args()

    if a.cmd == "post":
        text = open(a.file, encoding="utf-8").read() if a.file else a.text
        if not text or not text.strip():
            sys.exit("Nothing to post.")
        if a.re:
            done = [c for c in comments() if c["id"] > a.re and c["body"].lstrip().startswith(CHIEF_TAG)
                    and f"Re {a.re}" in c["body"]]
            if done:
                sys.exit(f"Already answered in #{done[0]['id']}: another Chief session acted on {a.re}. "
                         "Do not act or post again; run `read`.")
            body = text.lstrip()
            if body.startswith(CHIEF_TAG):
                body = body[len(CHIEF_TAG):].lstrip()
            if f"Re {a.re}" not in body:
                body = f"Re {a.re}: {body}"
            text = body
        if not text.lstrip().startswith(CHIEF_TAG):
            text = f"{CHIEF_TAG} {text}"
        c = api("POST", f"/issues/{PR}/comments", {"body": text})
        mark(c["id"])
        print("posted", c["html_url"])
    elif a.cmd == "read":
        seen = 0 if a.all else last_seen()
        new = [c for c in comments() if c["id"] > seen]
        for c in new:
            show(c)
        if new:
            mark(new[-1]["id"])
        else:
            print("No new messages.")
    elif a.cmd == "status":
        seen = last_seen()
        allc = comments()
        unread = [c for c in allc if c["id"] > seen and CLAUDE_MARK in c["body"]]
        last = allc[-1]["id"] if allc else 0
        if unread:
            print(f"UNREAD: {len(unread)} Claude message(s) since #{seen}, newest #{unread[-1]['id']} "
                  f"at {unread[-1]['created_at']}. Run `read` and act before reporting to Ben.")
            sys.exit(10)
        print(f"Up to date. Thread read to #{seen} (latest #{last}).")
    elif a.cmd == "wait":
        seen, end = last_seen(), time.time() + a.timeout
        while time.time() < end:
            new = [c for c in comments() if c["id"] > seen]
            replies = [c for c in new if CLAUDE_MARK in c["body"]]
            if replies:
                for c in new:
                    show(c)
                mark(new[-1]["id"])
                return
            time.sleep(60)
        sys.exit(f"No reply from Claude within {a.timeout} s.")


if __name__ == "__main__":
    main()
